[pytest]
# 命令行参数：-s 显示print，--alluredir 生成报告
addopts = -s --alluredir report --clean-alluredir
# 测试文件搜索路径
testpaths = ./scripts
# 文件名匹配规则
python_files = test_*.py
# 类名匹配规则
python_classes = Test*
# 方法名匹配规则
python_functions = test*
